{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-key",
    "version": "4.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.9.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "21.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-key-4.9.0-SNAPSHOT.jar",
          "url": "adventure-key-4.9.0-SNAPSHOT.jar",
          "size": 8199,
          "sha512": "afba2028bff9d9abecfbed868fa30938fe41e764f6dd5a86dd4d7e0b608878384bf5447d5881b33efc5c04cab76ad1bc2709ab5dba158cedd93e38eac14b79eb",
          "sha256": "453ca709f59afa33de6d508d599eeeb12cb3200cd3f83f13f8ae90bd5682ab77",
          "sha1": "e6b0df77f1ef1a78cb986ff85c604438dde388d7",
          "md5": "a0217d57d51d55bd91f93f9aed9fee99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.9.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-key-4.9.0-SNAPSHOT.jar",
          "url": "adventure-key-4.9.0-SNAPSHOT.jar",
          "size": 8199,
          "sha512": "afba2028bff9d9abecfbed868fa30938fe41e764f6dd5a86dd4d7e0b608878384bf5447d5881b33efc5c04cab76ad1bc2709ab5dba158cedd93e38eac14b79eb",
          "sha256": "453ca709f59afa33de6d508d599eeeb12cb3200cd3f83f13f8ae90bd5682ab77",
          "sha1": "e6b0df77f1ef1a78cb986ff85c604438dde388d7",
          "md5": "a0217d57d51d55bd91f93f9aed9fee99"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-key-4.9.0-SNAPSHOT-javadoc.jar",
          "url": "adventure-key-4.9.0-SNAPSHOT-javadoc.jar",
          "size": 410103,
          "sha512": "3c79ef51b9b88dd1693aff64dcf7b05b51845bd688811e8215cb0a029c0f5a02e92726f03fa6a5a24a262f3f8e8cc02d30827f0d5605ee341ba452fc199617d0",
          "sha256": "fc24bb637186d1640f857a57a4125cb8e0c15dd054feaf400ca052f6f6856364",
          "sha1": "5daf4b36832cdb4f83bbe5c0b2fadadd47f82854",
          "md5": "1723e3ccd65fe3f85bd9124e9d6f9e4f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-key-4.9.0-SNAPSHOT-sources.jar",
          "url": "adventure-key-4.9.0-SNAPSHOT-sources.jar",
          "size": 11323,
          "sha512": "906e3c569a120ff8d8d87620039a04525ff48885d8e510276db88ba728f3e049adbf0a737f1cb064ba7a6839da89c2325ad790f43dd0b713df40e920a466e678",
          "sha256": "e18a6386da6068d54a28fe80de18170591f98227db1374ed9c89181a02001e02",
          "sha1": "9075e0a5afe988c662a748d66b9c8226556c93dd",
          "md5": "aeb24cd860e216a5fb177558f45bf590"
        }
      ]
    }
  ]
}
